
version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_BASE_URL: ${VITE_BASE_URL}
    image: courses-app-fe:latest
    ports:
      - "5173:80"
    restart: unless-stopped
